//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runes_and_Spells.Content.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runes_and_Spells.Resources.Resources.ru", typeof(Resources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to новое.
        /// </summary>
        internal static string a_new {
            get {
                return ResourceManager.GetString("a new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to исследование?.
        /// </summary>
        internal static string adventure_ {
            get {
                return ResourceManager.GetString("adventure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воздух.
        /// </summary>
        internal static string air {
            get {
                return ResourceManager.GetString("air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены,\nчто хотите выйти?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_exit_ {
            get {
                return ResourceManager.GetString("Are you sure you want to exit?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В далеком краю странствовал один путешественник, \nпреследующий свою главную цель в жизни. Он долго скитался\nиз одного края мира в другой, изучая обряды и традиции,\nчтобы постичь столь хаотичную силу - магию..
        /// </summary>
        internal static string Backstory1 {
            get {
                return ResourceManager.GetString("Backstory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не упуская такой возможности, путник решает продолжить дело\nпрошлого хозяина и изучить этот удивительный мир магии.\nНо первым делом ему надо сделать свою первую\nв жизни руну, а потом и свой первый свиток магии..
        /// </summary>
        internal static string Backstory10 {
            get {
                return ResourceManager.GetString("Backstory10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В один из дней своего путешествия он забрел очень далеко \nв лес и заблудился. Усталость накатывала все сильнее,\nи уже начинало темнеть. Остаться спать в открытом\nместе означало бы гибель, ведь звери в этом лесу\nпросыпаются именно ночью..
        /// </summary>
        internal static string Backstory2 {
            get {
                return ResourceManager.GetString("Backstory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путешественнику пришлось идти всю ночь в поисках укрытия.\nВокруг то и дело были слышны ужасные вои и пугающие звуки..
        /// </summary>
        internal static string Backstory3 {
            get {
                return ResourceManager.GetString("Backstory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И вот, начало светать. Путник из последних сил забрался \nна высокий склон и, пристально оглядев округу, \nзаметил небольшую избушку..
        /// </summary>
        internal static string Backstory4 {
            get {
                return ResourceManager.GetString("Backstory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это был заброшенный дом, в котором уже давно никого не \nбыло. Обследуя свое новое укрытие он был очень \nудивлен - в доме находились вещи, про которые он как-то раз\nчитал в старых книгах: алтарь и магическая печь..
        /// </summary>
        internal static string Backstory5 {
            get {
                return ResourceManager.GetString("Backstory5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путник решил остаться в этом доме на несколько дней, \nчтобы передохнуть. На улице рядом с входной дверью \nнаходилась большая лужа грязи, которую было решено убрать..
        /// </summary>
        internal static string Backstory6 {
            get {
                return ResourceManager.GetString("Backstory6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На следующий день после уничтожения грязи,\nстранник впал в ступор - лужа снова была полная,\nкак будто он ее и не убирал..
        /// </summary>
        internal static string Backstory7 {
            get {
                return ResourceManager.GetString("Backstory7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимательно изучив эту необъяснимую на первый взгляд \nлужу грязи, путешественник пришел к выводу:\nэто вовсе не грязь, а магическая глина, \nспособная на регенерацию..
        /// </summary>
        internal static string Backstory8 {
            get {
                return ResourceManager.GetString("Backstory8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тогда к нему и пришло осознание: прошлый владелец дома \nзанимался созданием рун - древним способом хранить \nмагию в глине путем зачарования..
        /// </summary>
        internal static string Backstory9 {
            get {
                return ResourceManager.GetString("Backstory9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тьма.
        /// </summary>
        internal static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кровь.
        /// </summary>
        internal static string blood {
            get {
                return ResourceManager.GetString("blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка.
        /// </summary>
        internal static string Buy_Tab {
            get {
                return ResourceManager.GetString("Buy Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите слот.
        /// </summary>
        internal static string Choose_the_slot {
            get {
                return ResourceManager.GetString("Choose the slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Craft {
            get {
                return ResourceManager.GetString("Craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искажение.
        /// </summary>
        internal static string distorted {
            get {
                return ResourceManager.GetString("distorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эффекты.
        /// </summary>
        internal static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стихия.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой слот.
        /// </summary>
        internal static string Empty_slot {
            get {
                return ResourceManager.GetString("Empty slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Огонь.
        /// </summary>
        internal static string fire {
            get {
                return ResourceManager.GetString("fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный экран.
        /// </summary>
        internal static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдать.
        /// </summary>
        internal static string Give {
            get {
                return ResourceManager.GetString("Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Земля.
        /// </summary>
        internal static string grass {
            get {
                return ResourceManager.GetString("grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лед.
        /// </summary>
        internal static string ice {
            get {
                return ResourceManager.GetString("ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поехали!.
        /// </summary>
        internal static string Let_s_go_ {
            get {
                return ResourceManager.GetString("Let\'s go!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Луна.
        /// </summary>
        internal static string moon {
            get {
                return ResourceManager.GetString("moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музыка.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая игра.
        /// </summary>
        internal static string New_game {
            get {
                return ResourceManager.GetString("New game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стр..
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сила.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готовы начать.
        /// </summary>
        internal static string Ready_to_start {
            get {
                return ResourceManager.GetString("Ready to start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение.
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руна.
        /// </summary>
        internal static string Rune {
            get {
                return ResourceManager.GetString("Rune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слепок руны.
        /// </summary>
        internal static string Rune_cast {
            get {
                return ResourceManager.GetString("Rune cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руны.
        /// </summary>
        internal static string Runes {
            get {
                return ResourceManager.GetString("Runes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто рун.
        /// </summary>
        internal static string Runes_unlocked {
            get {
                return ResourceManager.GetString("Runes unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свиток.
        /// </summary>
        internal static string Scroll_of {
            get {
                return ResourceManager.GetString("Scroll of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свитки.
        /// </summary>
        internal static string Scrolls {
            get {
                return ResourceManager.GetString("Scrolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто свитков.
        /// </summary>
        internal static string Scrolls_unlocked {
            get {
                return ResourceManager.GetString("Scrolls unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажа.
        /// </summary>
        internal static string Sell_Tab {
            get {
                return ResourceManager.GetString("Sell Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слепок неизвестной руны.
        /// </summary>
        internal static string Unknown_rune_cast {
            get {
                return ResourceManager.GetString("Unknown rune cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный свиток.
        /// </summary>
        internal static string Unknown_scroll {
            get {
                return ResourceManager.GetString("Unknown scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Громкость.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кошель.
        /// </summary>
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вода.
        /// </summary>
        internal static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша позиция.
        /// </summary>
        internal static string Your_position {
            get {
                return ResourceManager.GetString("Your position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адского пламени.
        /// </summary>
        internal static string Адского_пламени {
            get {
                return ResourceManager.GetString("Адского пламени", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буйного роста.
        /// </summary>
        internal static string Буйного_роста {
            get {
                return ResourceManager.GetString("Буйного роста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстрой ковки.
        /// </summary>
        internal static string Быстрой_ковки {
            get {
                return ResourceManager.GetString("Быстрой ковки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вдохновения.
        /// </summary>
        internal static string Вдохновения {
            get {
                return ResourceManager.GetString("Вдохновения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взрыва.
        /// </summary>
        internal static string Взрыва {
            get {
                return ResourceManager.GetString("Взрыва", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водного потока.
        /// </summary>
        internal static string Водного_потока {
            get {
                return ResourceManager.GetString("Водного потока", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волшебный пергамент.
        /// </summary>
        internal static string Волшебный_пергамент {
            get {
                return ResourceManager.GetString("Волшебный пергамент", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галлюцинаций.
        /// </summary>
        internal static string Галлюцинаций {
            get {
                return ResourceManager.GetString("Галлюцинаций", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глина.
        /// </summary>
        internal static string Глина {
            get {
                return ResourceManager.GetString("Глина", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гниения.
        /// </summary>
        internal static string Гниения {
            get {
                return ResourceManager.GetString("Гниения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Древний изумрудный ключ.
        /// </summary>
        internal static string Древний_изумрудный_ключ {
            get {
                return ResourceManager.GetString("Древний изумрудный ключ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замедления.
        /// </summary>
        internal static string Замедления {
            get {
                return ResourceManager.GetString("Замедления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защиты от бури.
        /// </summary>
        internal static string Защиты_от_бури {
            get {
                return ResourceManager.GetString("Защиты от бури", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защиты от кислоты.
        /// </summary>
        internal static string Защиты_от_кислоты {
            get {
                return ResourceManager.GetString("Защиты от кислоты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защиты от магии.
        /// </summary>
        internal static string Защиты_от_магии {
            get {
                return ResourceManager.GetString("Защиты от магии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защиты от мороза.
        /// </summary>
        internal static string Защиты_от_мороза {
            get {
                return ResourceManager.GetString("Защиты от мороза", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защиты от огня.
        /// </summary>
        internal static string Защиты_от_огня {
            get {
                return ResourceManager.GetString("Защиты от огня", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Землекопа.
        /// </summary>
        internal static string Землекопа {
            get {
                return ResourceManager.GetString("Землекопа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дыхния землей.
        /// </summary>
        internal static string Земного_дыхания {
            get {
                return ResourceManager.GetString("Земного дыхания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Злобного огня.
        /// </summary>
        internal static string Злобного_огня {
            get {
                return ResourceManager.GetString("Злобного огня", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зловония.
        /// </summary>
        internal static string Зловония {
            get {
                return ResourceManager.GetString("Зловония", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извлечение\nэссенции.
        /// </summary>
        internal static string Извлечение_эссенции {
            get {
                return ResourceManager.GetString("Извлечение эссенции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Испепеления.
        /// </summary>
        internal static string Испепеления {
            get {
                return ResourceManager.GetString("Испепеления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каменной кожи.
        /// </summary>
        internal static string Каменной_кожи {
            get {
                return ResourceManager.GetString("Каменной кожи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кипячения.
        /// </summary>
        internal static string Кипячения {
            get {
                return ResourceManager.GetString("Кипячения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кислоты.
        /// </summary>
        internal static string Кислоты {
            get {
                return ResourceManager.GetString("Кислоты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кошмаров.
        /// </summary>
        internal static string Кошмаров {
            get {
                return ResourceManager.GetString("Кошмаров", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кусочки глины.
        /// </summary>
        internal static string Кусочки_глины {
            get {
                return ResourceManager.GetString("Кусочки глины", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крист. Лавы.
        /// </summary>
        internal static string Лавы {
            get {
                return ResourceManager.GetString("Лавы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Левитации.
        /// </summary>
        internal static string Левитации {
            get {
                return ResourceManager.GetString("Левитации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легкомыслия.
        /// </summary>
        internal static string Легкомыслия {
            get {
                return ResourceManager.GetString("Легкомыслия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ледяного дыхания.
        /// </summary>
        internal static string Ледяного_дыхания {
            get {
                return ResourceManager.GetString("Ледяного дыхания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ледяного хаоса.
        /// </summary>
        internal static string Ледяного_хаоса {
            get {
                return ResourceManager.GetString("Ледяного хаоса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ледяной ауры.
        /// </summary>
        internal static string Ледяной_ауры {
            get {
                return ResourceManager.GetString("Ледяной ауры", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ледяной феи.
        /// </summary>
        internal static string Ледяной_феи {
            get {
                return ResourceManager.GetString("Ледяной феи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лени.
        /// </summary>
        internal static string Лени {
            get {
                return ResourceManager.GetString("Лени", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечения.
        /// </summary>
        internal static string Лечения {
            get {
                return ResourceManager.GetString("Лечения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Либидо.
        /// </summary>
        internal static string Либидо {
            get {
                return ResourceManager.GetString("Либидо", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ловкости.
        /// </summary>
        internal static string Ловкости {
            get {
                return ResourceManager.GetString("Ловкости", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магического льда.
        /// </summary>
        internal static string Магического_льда {
            get {
                return ResourceManager.GetString("Магического льда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магической силы.
        /// </summary>
        internal static string Магической_силы {
            get {
                return ResourceManager.GetString("Магической силы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия ветра.
        /// </summary>
        internal static string Магия_ветра {
            get {
                return ResourceManager.GetString("Магия ветра", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия жизни.
        /// </summary>
        internal static string Магия_жизни {
            get {
                return ResourceManager.GetString("Магия жизни", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия льда.
        /// </summary>
        internal static string Магия_льда {
            get {
                return ResourceManager.GetString("Магия льда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия океана.
        /// </summary>
        internal static string Магия_океана {
            get {
                return ResourceManager.GetString("Магия океана", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия природы.
        /// </summary>
        internal static string Магия_природы {
            get {
                return ResourceManager.GetString("Магия природы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия солнца.
        /// </summary>
        internal static string Магия_солнца {
            get {
                return ResourceManager.GetString("Магия солнца", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия фей.
        /// </summary>
        internal static string Магия_фей {
            get {
                return ResourceManager.GetString("Магия фей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магия яда.
        /// </summary>
        internal static string Магия_яда {
            get {
                return ResourceManager.GetString("Магия яда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молнии.
        /// </summary>
        internal static string Молнии {
            get {
                return ResourceManager.GetString("Молнии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Морозной воды.
        /// </summary>
        internal static string Морозной_воды {
            get {
                return ResourceManager.GetString("Морозной воды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невидимости.
        /// </summary>
        internal static string Невидимости {
            get {
                return ResourceManager.GetString("Невидимости", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некромантии.
        /// </summary>
        internal static string Некромантии {
            get {
                return ResourceManager.GetString("Некромантии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неплодородия.
        /// </summary>
        internal static string Неплодородия {
            get {
                return ResourceManager.GetString("Неплодородия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обездвиживания.
        /// </summary>
        internal static string Обездвиживания {
            get {
                return ResourceManager.GetString("Обездвиживания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединение рун.
        /// </summary>
        internal static string Объединение_рун {
            get {
                return ResourceManager.GetString("Объединение рун", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Огненного смерча.
        /// </summary>
        internal static string Огненного_смерча {
            get {
                return ResourceManager.GetString("Огненного смерча", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окаменения.
        /// </summary>
        internal static string Окаменения {
            get {
                return ResourceManager.GetString("Окаменения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Омоложения.
        /// </summary>
        internal static string Омоложения {
            get {
                return ResourceManager.GetString("Омоложения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опьянения.
        /// </summary>
        internal static string Опьянения {
            get {
                return ResourceManager.GetString("Опьянения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осколка злобы.
        /// </summary>
        internal static string Осколка_злобы {
            get {
                return ResourceManager.GetString("Осколка злобы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отравления.
        /// </summary>
        internal static string Отравления {
            get {
                return ResourceManager.GetString("Отравления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оттепели.
        /// </summary>
        internal static string Оттепели {
            get {
                return ResourceManager.GetString("Оттепели", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очарования.
        /// </summary>
        internal static string Очарования {
            get {
                return ResourceManager.GetString("Очарования", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перышка.
        /// </summary>
        internal static string Перышка {
            get {
                return ResourceManager.GetString("Перышка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призыва огня.
        /// </summary>
        internal static string Призыва_огня {
            get {
                return ResourceManager.GetString("Призыва огня", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прилива.
        /// </summary>
        internal static string Прилива {
            get {
                return ResourceManager.GetString("Прилива", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проклятия.
        /// </summary>
        internal static string Проклятия {
            get {
                return ResourceManager.GetString("Проклятия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрыва материи.
        /// </summary>
        internal static string Разрыва_материи {
            get {
                return ResourceManager.GetString("Разрыва материи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регенерации.
        /// </summary>
        internal static string Регенерации {
            get {
                return ResourceManager.GetString("Регенерации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решительности.
        /// </summary>
        internal static string Решительности {
            get {
                return ResourceManager.GetString("Решительности", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Света.
        /// </summary>
        internal static string Света {
            get {
                return ResourceManager.GetString("Света", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Силы.
        /// </summary>
        internal static string Силы {
            get {
                return ResourceManager.GetString("Силы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склейки.
        /// </summary>
        internal static string Склейки {
            get {
                return ResourceManager.GetString("Склейки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скольжения.
        /// </summary>
        internal static string Скольжения {
            get {
                return ResourceManager.GetString("Скольжения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слепоты.
        /// </summary>
        internal static string Слепоты {
            get {
                return ResourceManager.GetString("Слепоты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сна.
        /// </summary>
        internal static string Сна {
            get {
                return ResourceManager.GetString("Сна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снега.
        /// </summary>
        internal static string Снега {
            get {
                return ResourceManager.GetString("Снега", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снежного бурана.
        /// </summary>
        internal static string Снежного_бурана {
            get {
                return ResourceManager.GetString("Снежного бурана", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятия порчи.
        /// </summary>
        internal static string Снятия_порчи {
            get {
                return ResourceManager.GetString("Снятия порчи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сосульки.
        /// </summary>
        internal static string Сосульки {
            get {
                return ResourceManager.GetString("Сосульки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стальной кожи.
        /// </summary>
        internal static string Стальной_кожи {
            get {
                return ResourceManager.GetString("Стальной кожи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старения.
        /// </summary>
        internal static string Старения {
            get {
                return ResourceManager.GetString("Старения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый золотой ключ.
        /// </summary>
        internal static string Старый_золотой_ключ {
            get {
                return ResourceManager.GetString("Старый золотой ключ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый серебряный ключ.
        /// </summary>
        internal static string Старый_серебряный_ключ {
            get {
                return ResourceManager.GetString("Старый серебряный ключ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страха.
        /// </summary>
        internal static string Страха {
            get {
                return ResourceManager.GetString("Страха", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темная магия.
        /// </summary>
        internal static string Темная_магия {
            get {
                return ResourceManager.GetString("Темная магия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теплого пламени.
        /// </summary>
        internal static string Теплого_пламени {
            get {
                return ResourceManager.GetString("Теплого пламени", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тумана.
        /// </summary>
        internal static string Тумана {
            get {
                return ResourceManager.GetString("Тумана", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удачной рыбалки.
        /// </summary>
        internal static string Удачной_рыбалки {
            get {
                return ResourceManager.GetString("Удачной рыбалки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удачных событий.
        /// </summary>
        internal static string Удачных_событий {
            get {
                return ResourceManager.GetString("Удачных событий", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управл. кровью.
        /// </summary>
        internal static string Управл__кровью {
            get {
                return ResourceManager.GetString("Управл. кровью", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усиление руны.
        /// </summary>
        internal static string Усиление_руны {
            get {
                return ResourceManager.GetString("Усиление руны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хладнокровия.
        /// </summary>
        internal static string Хладнокровия {
            get {
                return ResourceManager.GetString("Хладнокровия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хождения во сне.
        /// </summary>
        internal static string Хождения_во_сне {
            get {
                return ResourceManager.GetString("Хождения во сне", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хождения по воде.
        /// </summary>
        internal static string Хождения_по_воде {
            get {
                return ResourceManager.GetString("Хождения по воде", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена продажи.
        /// </summary>
        internal static string Цена_продажи {
            get {
                return ResourceManager.GetString("Цена продажи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шипов.
        /// </summary>
        internal static string Шипов {
            get {
                return ResourceManager.GetString("Шипов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эссенция руны.
        /// </summary>
        internal static string Эссенция_руны {
            get {
                return ResourceManager.GetString("Эссенция руны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ядовитого льда.
        /// </summary>
        internal static string Ядовитого_льда {
            get {
                return ResourceManager.GetString("Ядовитого льда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярости.
        /// </summary>
        internal static string Ярости {
            get {
                return ResourceManager.GetString("Ярости", resourceCulture);
            }
        }
    }
}
