//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runes_and_Spells.Content.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runes_and_Spells.Resources.Resources.en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a new.
        /// </summary>
        internal static string a_new {
            get {
                return ResourceManager.GetString("a new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adventure?.
        /// </summary>
        internal static string adventure_ {
            get {
                return ResourceManager.GetString("adventure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string air {
            get {
                return ResourceManager.GetString("air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure\nyou want to exit?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_exit_ {
            get {
                return ResourceManager.GetString("Are you sure you want to exit?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a distant land, a traveler wandered, pursuing his\nmain goal in life. He wandered for a long time from one\nend of the world to another, studying rituals and\ntraditions in order to comprehend such a chaotic force - magic..
        /// </summary>
        internal static string Backstory1 {
            get {
                return ResourceManager.GetString("Backstory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not missing this opportunity, the traveler decides to continue \nthe work of the past owner and explore this\nwonderful world of magic. But first of all, he needs to make\nhis first rune in his life, and then his first scroll of magic..
        /// </summary>
        internal static string Backstory10 {
            get {
                return ResourceManager.GetString("Backstory10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On one of the days of his journey, he wandered very far into\nthe forest and got lost. Fatigue grew stronger. It was already dark.\nTo sleep in an open place would mean death,\nbecause the animals in this forest wake up at night..
        /// </summary>
        internal static string Backstory2 {
            get {
                return ResourceManager.GetString("Backstory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The traveler had to walk all night in search of shelter.\nFrightful howls and frightening sounds were heard all around..
        /// </summary>
        internal static string Backstory3 {
            get {
                return ResourceManager.GetString("Backstory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And so, it began to light up. With the last of his strength,\nthe traveler climbed up a high mountain and,\nlooking intently around the area, noted a small hut..
        /// </summary>
        internal static string Backstory4 {
            get {
                return ResourceManager.GetString("Backstory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was an abandoned house that had been empty for a long time.\nWhile examining his dwelling, the wanderer was very \nsurprised - in the house there were things that he once \nread in old books: an altar and a magic furnace..
        /// </summary>
        internal static string Backstory5 {
            get {
                return ResourceManager.GetString("Backstory5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The traveler decided to stay in this house for a few days to rest.\nThere was a large puddle of dirt on the street near the front door,\nwhich it was decided to clean up..
        /// </summary>
        internal static string Backstory6 {
            get {
                return ResourceManager.GetString("Backstory6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next day after cleaning up the dirt, the stranger was at a loss -\nthe puddle was full again, as if he hadn&apos;t cleaned it up..
        /// </summary>
        internal static string Backstory7 {
            get {
                return ResourceManager.GetString("Backstory7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After carefully examining this seemingly inexplicable pool of mud,\nthe traveler came to the conclusion: this is not mud at all,\nbut magical clay capable of regeneration..
        /// </summary>
        internal static string Backstory8 {
            get {
                return ResourceManager.GetString("Backstory8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then the realization came to him: the previous owner of the house \nwas engaged in the creation of runes -\nan ancient way to store magic in clay by enchantment..
        /// </summary>
        internal static string Backstory9 {
            get {
                return ResourceManager.GetString("Backstory9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood.
        /// </summary>
        internal static string blood {
            get {
                return ResourceManager.GetString("blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy_Tab {
            get {
                return ResourceManager.GetString("Buy Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the slot.
        /// </summary>
        internal static string Choose_the_slot {
            get {
                return ResourceManager.GetString("Choose the slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft.
        /// </summary>
        internal static string Craft {
            get {
                return ResourceManager.GetString("Craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distortion.
        /// </summary>
        internal static string distorted {
            get {
                return ResourceManager.GetString("distorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        internal static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty slot.
        /// </summary>
        internal static string Empty_slot {
            get {
                return ResourceManager.GetString("Empty slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string fire {
            get {
                return ResourceManager.GetString("fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string Give {
            get {
                return ResourceManager.GetString("Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string grass {
            get {
                return ResourceManager.GetString("grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string ice {
            get {
                return ResourceManager.GetString("ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go!.
        /// </summary>
        internal static string Let_s_go_ {
            get {
                return ResourceManager.GetString("Let\'s go!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        internal static string moon {
            get {
                return ResourceManager.GetString("moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string New_game {
            get {
                return ResourceManager.GetString("New game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start.
        /// </summary>
        internal static string Ready_to_start {
            get {
                return ResourceManager.GetString("Ready to start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune.
        /// </summary>
        internal static string Rune {
            get {
                return ResourceManager.GetString("Rune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune cast.
        /// </summary>
        internal static string Rune_cast {
            get {
                return ResourceManager.GetString("Rune cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes.
        /// </summary>
        internal static string Runes {
            get {
                return ResourceManager.GetString("Runes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes unlocked.
        /// </summary>
        internal static string Runes_unlocked {
            get {
                return ResourceManager.GetString("Runes unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll of.
        /// </summary>
        internal static string Scroll_of {
            get {
                return ResourceManager.GetString("Scroll of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolls.
        /// </summary>
        internal static string Scrolls {
            get {
                return ResourceManager.GetString("Scrolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolls unlocked.
        /// </summary>
        internal static string Scrolls_unlocked {
            get {
                return ResourceManager.GetString("Scrolls unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string Sell_Tab {
            get {
                return ResourceManager.GetString("Sell Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown rune cast.
        /// </summary>
        internal static string Unknown_rune_cast {
            get {
                return ResourceManager.GetString("Unknown rune cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown scroll.
        /// </summary>
        internal static string Unknown_scroll {
            get {
                return ResourceManager.GetString("Unknown scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your position.
        /// </summary>
        internal static string Your_position {
            get {
                return ResourceManager.GetString("Your position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellfire.
        /// </summary>
        internal static string Адского_пламени {
            get {
                return ResourceManager.GetString("Адского пламени", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild growth.
        /// </summary>
        internal static string Буйного_роста {
            get {
                return ResourceManager.GetString("Буйного роста", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick forging.
        /// </summary>
        internal static string Быстрой_ковки {
            get {
                return ResourceManager.GetString("Быстрой ковки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiration.
        /// </summary>
        internal static string Вдохновения {
            get {
                return ResourceManager.GetString("Вдохновения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion.
        /// </summary>
        internal static string Взрыва {
            get {
                return ResourceManager.GetString("Взрыва", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water stream.
        /// </summary>
        internal static string Водного_потока {
            get {
                return ResourceManager.GetString("Водного потока", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic parchment.
        /// </summary>
        internal static string Волшебный_пергамент {
            get {
                return ResourceManager.GetString("Волшебный пергамент", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallucinations.
        /// </summary>
        internal static string Галлюцинаций {
            get {
                return ResourceManager.GetString("Галлюцинаций", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay.
        /// </summary>
        internal static string Глина {
            get {
                return ResourceManager.GetString("Глина", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotting.
        /// </summary>
        internal static string Гниения {
            get {
                return ResourceManager.GetString("Гниения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient emerald key.
        /// </summary>
        internal static string Древний_изумрудный_ключ {
            get {
                return ResourceManager.GetString("Древний изумрудный ключ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowness.
        /// </summary>
        internal static string Замедления {
            get {
                return ResourceManager.GetString("Замедления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm protection.
        /// </summary>
        internal static string Защиты_от_бури {
            get {
                return ResourceManager.GetString("Защиты от бури", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid protection.
        /// </summary>
        internal static string Защиты_от_кислоты {
            get {
                return ResourceManager.GetString("Защиты от кислоты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic protection.
        /// </summary>
        internal static string Защиты_от_магии {
            get {
                return ResourceManager.GetString("Защиты от магии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost protection.
        /// </summary>
        internal static string Защиты_от_мороза {
            get {
                return ResourceManager.GetString("Защиты от мороза", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire protection.
        /// </summary>
        internal static string Защиты_от_огня {
            get {
                return ResourceManager.GetString("Защиты от огня", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digging.
        /// </summary>
        internal static string Землекопа {
            get {
                return ResourceManager.GetString("Землекопа", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthbreath.
        /// </summary>
        internal static string Земного_дыхания {
            get {
                return ResourceManager.GetString("Земного дыхания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evil fire.
        /// </summary>
        internal static string Злобного_огня {
            get {
                return ResourceManager.GetString("Злобного огня", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stench.
        /// </summary>
        internal static string Зловония {
            get {
                return ResourceManager.GetString("Зловония", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essence\nextraction.
        /// </summary>
        internal static string Извлечение_эссенции {
            get {
                return ResourceManager.GetString("Извлечение эссенции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incinerate.
        /// </summary>
        internal static string Испепеления {
            get {
                return ResourceManager.GetString("Испепеления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoneskin.
        /// </summary>
        internal static string Каменной_кожи {
            get {
                return ResourceManager.GetString("Каменной кожи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boil.
        /// </summary>
        internal static string Кипячения {
            get {
                return ResourceManager.GetString("Кипячения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid.
        /// </summary>
        internal static string Кислоты {
            get {
                return ResourceManager.GetString("Кислоты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        internal static string Кошмаров {
            get {
                return ResourceManager.GetString("Кошмаров", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay pieces.
        /// </summary>
        internal static string Кусочки_глины {
            get {
                return ResourceManager.GetString("Кусочки глины", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal lava.
        /// </summary>
        internal static string Лавы {
            get {
                return ResourceManager.GetString("Лавы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levitation.
        /// </summary>
        internal static string Левитации {
            get {
                return ResourceManager.GetString("Левитации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frivolity.
        /// </summary>
        internal static string Легкомыслия {
            get {
                return ResourceManager.GetString("Легкомыслия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Breath.
        /// </summary>
        internal static string Ледяного_дыхания {
            get {
                return ResourceManager.GetString("Ледяного дыхания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Chaos.
        /// </summary>
        internal static string Ледяного_хаоса {
            get {
                return ResourceManager.GetString("Ледяного хаоса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Aura.
        /// </summary>
        internal static string Ледяной_ауры {
            get {
                return ResourceManager.GetString("Ледяной ауры", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice fairy.
        /// </summary>
        internal static string Ледяной_феи {
            get {
                return ResourceManager.GetString("Ледяной феи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloth.
        /// </summary>
        internal static string Лени {
            get {
                return ResourceManager.GetString("Лени", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        internal static string Лечения {
            get {
                return ResourceManager.GetString("Лечения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libido.
        /// </summary>
        internal static string Либидо {
            get {
                return ResourceManager.GetString("Либидо", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string Ловкости {
            get {
                return ResourceManager.GetString("Ловкости", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Ice.
        /// </summary>
        internal static string Магического_льда {
            get {
                return ResourceManager.GetString("Магического льда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic power.
        /// </summary>
        internal static string Магической_силы {
            get {
                return ResourceManager.GetString("Магической силы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind magic.
        /// </summary>
        internal static string Магия_ветра {
            get {
                return ResourceManager.GetString("Магия ветра", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic of life.
        /// </summary>
        internal static string Магия_жизни {
            get {
                return ResourceManager.GetString("Магия жизни", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice magic.
        /// </summary>
        internal static string Магия_льда {
            get {
                return ResourceManager.GetString("Магия льда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean magic.
        /// </summary>
        internal static string Магия_океана {
            get {
                return ResourceManager.GetString("Магия океана", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural magic.
        /// </summary>
        internal static string Магия_природы {
            get {
                return ResourceManager.GetString("Магия природы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun magic.
        /// </summary>
        internal static string Магия_солнца {
            get {
                return ResourceManager.GetString("Магия солнца", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy magic.
        /// </summary>
        internal static string Магия_фей {
            get {
                return ResourceManager.GetString("Магия фей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison magic.
        /// </summary>
        internal static string Магия_яда {
            get {
                return ResourceManager.GetString("Магия яда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning.
        /// </summary>
        internal static string Молнии {
            get {
                return ResourceManager.GetString("Молнии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frostwater.
        /// </summary>
        internal static string Морозной_воды {
            get {
                return ResourceManager.GetString("Морозной воды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisibility.
        /// </summary>
        internal static string Невидимости {
            get {
                return ResourceManager.GetString("Невидимости", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancy.
        /// </summary>
        internal static string Некромантии {
            get {
                return ResourceManager.GetString("Некромантии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infertility.
        /// </summary>
        internal static string Неплодородия {
            get {
                return ResourceManager.GetString("Неплодородия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immobilization.
        /// </summary>
        internal static string Обездвиживания {
            get {
                return ResourceManager.GetString("Обездвиживания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune fusion.
        /// </summary>
        internal static string Объединение_рун {
            get {
                return ResourceManager.GetString("Объединение рун", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firestorm.
        /// </summary>
        internal static string Огненного_смерча {
            get {
                return ResourceManager.GetString("Огненного смерча", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrification.
        /// </summary>
        internal static string Окаменения {
            get {
                return ResourceManager.GetString("Окаменения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejuvenation.
        /// </summary>
        internal static string Омоложения {
            get {
                return ResourceManager.GetString("Омоложения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intoxication.
        /// </summary>
        internal static string Опьянения {
            get {
                return ResourceManager.GetString("Опьянения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shard of Malice.
        /// </summary>
        internal static string Осколка_злобы {
            get {
                return ResourceManager.GetString("Осколка злобы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        internal static string Отравления {
            get {
                return ResourceManager.GetString("Отравления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming.
        /// </summary>
        internal static string Оттепели {
            get {
                return ResourceManager.GetString("Оттепели", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm.
        /// </summary>
        internal static string Очарования {
            get {
                return ResourceManager.GetString("Очарования", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feather.
        /// </summary>
        internal static string Перышка {
            get {
                return ResourceManager.GetString("Перышка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon fire.
        /// </summary>
        internal static string Призыва_огня {
            get {
                return ResourceManager.GetString("Призыва огня", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide.
        /// </summary>
        internal static string Прилива {
            get {
                return ResourceManager.GetString("Прилива", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curse.
        /// </summary>
        internal static string Проклятия {
            get {
                return ResourceManager.GetString("Проклятия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rupture of matter.
        /// </summary>
        internal static string Разрыва_материи {
            get {
                return ResourceManager.GetString("Разрыва материи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regeneration.
        /// </summary>
        internal static string Регенерации {
            get {
                return ResourceManager.GetString("Регенерации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisiveness.
        /// </summary>
        internal static string Решительности {
            get {
                return ResourceManager.GetString("Решительности", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Света {
            get {
                return ResourceManager.GetString("Света", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Силы {
            get {
                return ResourceManager.GetString("Силы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonding.
        /// </summary>
        internal static string Склейки {
            get {
                return ResourceManager.GetString("Склейки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding.
        /// </summary>
        internal static string Скольжения {
            get {
                return ResourceManager.GetString("Скольжения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blindness.
        /// </summary>
        internal static string Слепоты {
            get {
                return ResourceManager.GetString("Слепоты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string Сна {
            get {
                return ResourceManager.GetString("Сна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string Снега {
            get {
                return ResourceManager.GetString("Снега", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard.
        /// </summary>
        internal static string Снежного_бурана {
            get {
                return ResourceManager.GetString("Снежного бурана", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove curse.
        /// </summary>
        internal static string Снятия_порчи {
            get {
                return ResourceManager.GetString("Снятия порчи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icicle.
        /// </summary>
        internal static string Сосульки {
            get {
                return ResourceManager.GetString("Сосульки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steelskin.
        /// </summary>
        internal static string Стальной_кожи {
            get {
                return ResourceManager.GetString("Стальной кожи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aging.
        /// </summary>
        internal static string Старения {
            get {
                return ResourceManager.GetString("Старения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old golden key.
        /// </summary>
        internal static string Старый_золотой_ключ {
            get {
                return ResourceManager.GetString("Старый золотой ключ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old silver key.
        /// </summary>
        internal static string Старый_серебряный_ключ {
            get {
                return ResourceManager.GetString("Старый серебряный ключ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fear.
        /// </summary>
        internal static string Страха {
            get {
                return ResourceManager.GetString("Страха", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark magic.
        /// </summary>
        internal static string Темная_магия {
            get {
                return ResourceManager.GetString("Темная магия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Flame.
        /// </summary>
        internal static string Теплого_пламени {
            get {
                return ResourceManager.GetString("Теплого пламени", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mist.
        /// </summary>
        internal static string Тумана {
            get {
                return ResourceManager.GetString("Тумана", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good fishing.
        /// </summary>
        internal static string Удачной_рыбалки {
            get {
                return ResourceManager.GetString("Удачной рыбалки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortunate Events.
        /// </summary>
        internal static string Удачных_событий {
            get {
                return ResourceManager.GetString("Удачных событий", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood control.
        /// </summary>
        internal static string Управл__кровью {
            get {
                return ResourceManager.GetString("Управл. кровью", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune\nempowerment.
        /// </summary>
        internal static string Усиление_руны {
            get {
                return ResourceManager.GetString("Усиление руны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composure.
        /// </summary>
        internal static string Хладнокровия {
            get {
                return ResourceManager.GetString("Хладнокровия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleepwalking.
        /// </summary>
        internal static string Хождения_во_сне {
            get {
                return ResourceManager.GetString("Хождения во сне", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking on water.
        /// </summary>
        internal static string Хождения_по_воде {
            get {
                return ResourceManager.GetString("Хождения по воде", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell price.
        /// </summary>
        internal static string Цена_продажи {
            get {
                return ResourceManager.GetString("Цена продажи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thorns.
        /// </summary>
        internal static string Шипов {
            get {
                return ResourceManager.GetString("Шипов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune essence.
        /// </summary>
        internal static string Эссенция_руны {
            get {
                return ResourceManager.GetString("Эссенция руны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Ice.
        /// </summary>
        internal static string Ядовитого_льда {
            get {
                return ResourceManager.GetString("Ядовитого льда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage.
        /// </summary>
        internal static string Ярости {
            get {
                return ResourceManager.GetString("Ярости", resourceCulture);
            }
        }
    }
}
